version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
    commands:
      - echo install phase start...
      - echo install hexo
      - npm install -g hexo
      - echo node -v
      - node -v
      - echo npm -v
      - npm -v
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo build phase start...
      - hexo generate
      - echo ls
      - ls -la
      - echo build phase conpleted.
artifacts:
  files:
    - '**/*'
  base-directory: 'public'
